### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Grownz** [rhymes-ai/Allegro#11]
When I try to run the script, the following error message appears:
![grafik](https://github.com/user-attachments/assets/fd7afebe-c679-485f-b88d-580eee7f4464)

CUDA and python should be up to date:
![grafik](https://github.com/user-attachments/assets/ab203c0d-fd41-42b7-b02b-6388f0dd24f3)

and the correct Torch version is also pulled when installing requirements:
![grafik](https://github.com/user-attachments/assets/19232dc8-eb1f-4717-b9f3-1b299c8f501b)

How could the error have come about? Am I overlooking something, am I doing something wrong?
I have passed the following prompt:
![grafik](https://github.com/user-attachments/assets/613c5e61-32fa-46a1-8328-26de12e65642)

Thank you in advance :)

**Comment by hyang0511** [comment]
Would it be possible for you to test the following code in your environment?

`
import torch

print(torch.cuda.is_available())
`

**Comment by Grownz** [comment]
That in fact led me one step further! It returned as false. so i installed Pytorch with cuda manually (although it should be included in the requrements...).

in my case with this (depends on a few factors, see: https://pytorch.org/)
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Then the code returned as true (and i got forwarded to the next problem, but this one is fine, now).
![grafik](https://github.com/user-attachments/assets/0ff40125-9c2d-42db-b99a-191be2d761c9)


Thank you!
