### ISSUE TITLE
About the evaluation results

### ISSUE THREAD

**Issue by 963658029** [rhymes-ai/Allegro#14]
Thanks for your great work! I noticed that the motion amplitude in the results you showcased is quite good, but the motion score of vbench doesn't seem to be much different. Maybe you can try using ChronoMagic-Bench (e.g., GPT4o-MTScore), which CogVideoX also uses, as it defines it as the movement of fine details. I would like to see what the actual range of motion looks like.
![image](https://github.com/user-attachments/assets/b5effd06-c5e4-4e21-8ab8-f63b55d24e11)

**Comment by nightsnack** [comment]
Thanks. We will consider your suggestion.

**Comment by 963658029** [comment]
looking forward to the results
