### ISSUE TITLE
Which version of CogVideoX is used for comparison in the paper?

### ISSUE THREAD

**Issue by trouble-maker007** [rhymes-ai/Allegro#26]
2B or 5B？

**Comment by nightsnack** [comment]
We use the [智谱清影online version](chatglm.cn/video). They didn't say whether they use 2B or 5B.
 For VBench (Table 4), we mentioned in section 5.2 that we list CogVideoX-2B in Table 4.

**Comment by hyang0511** [comment]
We use CogVideoX-2B for both VBench and the user study.
