### ISSUE TITLE
Is it possible to throttle this app?

### ISSUE THREAD

**Issue by DataJuggler** [rhymes-ai/Allegro#27]
I installed this with no problems then I read the takes about an hour with a 3090, which I have a 3090, but my GPU starts crunching at full speed mode and I would rather not have an hour of full speed.

I don't know if this is possible and I know it would take longer to be batched or throttled, but if there is a way to process in chunks in a que or even a pause between the 88 images I think it would be a little less disruptive for people on their home PC's.

Thanks

**Comment by hyang0511** [comment]
Thanks for the suggestion. We have released the multi-GPU inference code with context-parallel and PAB under VideoSys (https://github.com/NUS-HPC-AI-Lab/VideoSys/pull/232). If everything goes well, the PR will be merged.

We are also working on other noise schedulers to reduce the inference steps. Hope we can release it soon.

**Comment by DataJuggler** [comment]
Thanks for the update.
