### ISSUE TITLE
Please provide the filenames of the models you need.

### ISSUE THREAD

**Issue by CHK-0000** [rhymes-ai/Allegro#3]
Invalid model weight name for the text encoder folder, resulting in an error. Please provide the correct filename.

**Comment by nightsnack** [comment]
I do not really understand this. Could you provide more information, like your transformers version? `pip show transformers`
Did you download the model weights on [https://huggingface.co/rhymes-ai/Allegro](https://huggingface.co/rhymes-ai/Allegro) ？

**Comment by nightsnack** [comment]
Could you please provide your transformers version? The folder name remains the same as huggingface hub.
 Or another way is to directly load the text encoder from [https://huggingface.co/DeepFloyd/t5-v1_1-xxl](https://huggingface.co/DeepFloyd/t5-v1_1-xxl). We didn't change the text encoder.

**Comment by CHK-0000** [comment]
transformers version is 4.40.1, If you have the same folder name as the one in the huggingface, and the same filename for each model in the folder, you will get an error.

**Comment by nitinmukesh** [comment]
@CHK-0000 

Use this and download files in text_encoder folder. Delete any existing files
https://huggingface.co/DeepFloyd/t5-v1_1-xxl
