### ISSUE TITLE
About semantic consistency>0.7 in  Text-to-Video Fine-tuning? 

### ISSUE THREAD

**Issue by lishiyuwhu** [rhymes-ai/Allegro#30]
Maybe it should be  the average LPIPS distance between each pair of frames in the video clip. 
A smaller value indicates higher similarity, reflecting better semantic consistency.

But in Text-to-Video Fine-tuning stage, Semantic Consistency (LPIPS score)>0.07.   It's to get more complex video,  not for more stable video?

**Comment by hyang0511** [comment]
Yes. 

As we want the model to generate videos with more dynamics at the SFT stage, we choose an LPIPS score > 0.07 to remove stable videos (especially those made of a single image with some simple transformations).
