### ISSUE TITLE
Question about default prompt tokens: training-specific or general guidance?

### ISSUE THREAD

**Issue by ai-anchorite** [rhymes-ai/Allegro#32]
Hi! 👋

First of all, thank you for making this model available to the community! The results are really impressive and I'm excited to see your future developments.

I have a technical question about the default prompts included in the inference pipeline:

```
(masterpiece), (best quality), (ultra-detailed), (unwatermarked),
{}
emotional, harmonious, vignette, 4k epic detailed, shot on kodak, 35mm photo,
sharp focus, high budget, cinemascope, moody, epic, gorgeous
```
I'm curious about how these specific prompt terms were chosen:

Were they specifically used during the model's training process as conditioning tokens?
Or are they more like general guidance terms that work well with the base architecture (similar to how they're used in standard Stable Diffusion pipelines)?

Understanding this would help me better utilize the model. Thanks in advance! 🙏

I'm also very excited about the upcoming TI2V.

**Comment by hyang0511** [comment]
No, both of the positive/negative system prompts are not included in the model training. They are more like some general guidance to make the output video looks better.
