### ISSUE TITLE
Issues with Multi-GPU Inference

### ISSUE THREAD

**Issue by agneet42** [rhymes-ai/Allegro#33]
Hi, 
When I try to run multi-GPU inference, it errors out here : https://github.com/nightsnack/Allegro-VideoSys/blob/master/videosys/models/transformers/allegro_transformer_3d.py#L66C35-L66C40 ; is there a known issue?

**Comment by nightsnack** [comment]
Oops, it's a bug. I forget to rename it. Let me fix it.

**Comment by nightsnack** [comment]
fixed. Simply remove this line solves the problem.

**Comment by agneet42** [comment]
thanks! multi-gpu works well now. Is there some working following up which reduces the latency? takes about ~5 mins on 8x A100 for 1 video.

**Comment by nightsnack** [comment]
Yes. I can provide some ideas.
1. Use cudnn backend as attention backend seems faster than flash-attn.
```python
with sdpa_kernel(SDPBackend.CUDNN_ATTENTION):
                hidden_states = F.scaled_dot_product_attention(
                    query, key, value, dropout_p=0.0, is_causal=False
                )
```
In current code, I only include flash-attn and xformers as attention backend in attention processor. 

2. Torch.compile 
If you generate several videos at a time, spending some time to compile the model can further speed up.
