### ISSUE TITLE
Will you release the LongTake-HD dataset?

### ISSUE THREAD

**Issue by HWT-WalterHu** [rhymes-ai/Allegro#43]
I just read your paper on long video generation and mentioned the  LongTake-HD dataset. Will you release the dataset downloading?

**Comment by Cakeyan** [comment]
Hi, thank you for your attention. We are now collecting the necessary code to construct datasets. Please wait for some time.

Moreover, Presto may be released in another repo. I will leave a comment here in the future.

**Comment by Cakeyan** [comment]
Hi all, we will release the Presto code, model and else in the [link](https://github.com/Cakeyan/Presto).
