### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./checkpoints/Allegro/text_encoder

### ISSUE THREAD

**Issue by nitinmukesh** [rhymes-ai/Allegro#9]
> OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./checkpoints/Allegro/text_encoder.

![image](https://github.com/user-attachments/assets/053ebd5c-8ee6-4a82-8d47-a7c325b18f36)

Please update the missing files
https://huggingface.co/rhymes-ai/Allegro/tree/main/text_encoder

Also change the name
pytorch_model.bin.index.json
TO
index.json

@nina-summer 
Please could you help.

**Comment by nightsnack** [comment]
Could you provide your transformer version? `pip show transformers`
We use the T5 model from [https://huggingface.co/DeepFloyd/t5-v1_1-xxl/tree/main](https://huggingface.co/DeepFloyd/t5-v1_1-xxl/tree/main) I have never seen those files before.
